buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://artifacts.elastic.co/maven' }
    }
    dependencies {
        classpath "org.elasticsearch.gradle:build-tools:8.5.0"
    }
}

apply plugin: 'java'
apply plugin: 'elasticsearch.esplugin'
apply plugin: 'elasticsearch.yaml-rest-test'

group = 'org.elasticsearch.lsena'
version = '8.5.0'

repositories {
    mavenCentral()
    maven { url 'https://artifacts.elastic.co/maven' }
}

dependencies {
    implementation 'org.elasticsearch:elasticsearch:8.5.0'
    implementation 'org.roaringbitmap:RoaringBitmap:0.9.35'
    yamlRestTestRuntimeOnly "org.apache.logging.log4j:log4j-core:1.2.17"
}

esplugin {
    name 'fastfilter-elasticsearch-plugin'
    description 'Filter large lists of integers using RoaringBitmap'
    classname 'org.elasticsearch.lsena.fastfilter.FastFilterPlugin'
    licenseFile rootProject.file("LICENSE.txt")
    noticeFile rootProject.file("NOTICE.txt")
}